apiVersion: kapp.k14s.io/v1alpha1
kind: Config
templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
  affectedResources:
    objectReferences:
    - path: [spec, virtualhost, tls]
      nameKey: secretName
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: projectcontour.io/v1, kind: HTTPProxy}

---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
templateRules:
- resourceMatchers:
  - apiVersionKindMatcher: {apiVersion: v1, kind: Secret}
  affectedResources:
    objectReferences:
    - path: [data]
      resourceMatchers:
      - apiVersionKindMatcher: {apiVersion: v1, kind: ConfigMap}
      nameKey: CONTOUR_TLS_SECRET_NAME
